# Aggregate Demand and Aggregate Supply {#ADAS}

## Introduction

This chapter focuses on the causes of short-run fluctuations in economic activity.

Economic activity fluctuates from year to year.
Real GDP increases in most years.
On average over the past 50 years, real GDP in the U.S. economy has grown by about 3 percent per year.
Real GDP per person has grown at the rate of about 2 percent per year over the past century.
In some years normal growth does not occur, causing a recession.  

A _recession_ is a period of declining real incomes, and rising unemployment.
A _depression_ is a severe recession.
An _expansion_ is a period of increasing real incomes, and falling unemployment.
A _boom_ is a strong expansion

Economic fluctuations are irregular and unpredictable.
Fluctuations in the economy are often called the business cycle.
Most macroeconomic variables fluctuate together.
As output falls, unemployment rises.

Recessions start at the _peak_ of a business cycle and end at the _trough._ 
The _length of a business cycle_ may be measured by the time between one peak and the next or the time between one trough and the next.
The peaks and troughs of the US business cycle are officially registered by the NBER.
During 1945-2009, there have been 11 cycles in the US. 
The average recession lasted 11 months and the average expansion lasted 59 months, thereby making the average cycle roughly 70 months long.

<!--See Figure 1 (a), next slide-->

In the US, there were recessions in 1980 and 1982, just two years apart.
On the other hand, there were no recessions between 1991 and 2001.

<!-- Figure 1 A Look at Short-Run Economic Fluctuations (a)-->

When real GDP falls in a recession, so do many other variables:
personal income, corporate profits, consumption spending, investment spending, industrial production, retail sales, home sales, auto sales, etc.
However, investment fluctuates a lot more than other variables. 
Even though investment is about one-seventh of GDP, much of the fall in GDP during recessions is due to the fall in investment spending.

<!-- See Figure 1 (b), next slide-->

The unemployment rate never approaches zero; instead it fluctuates around its natural rate, which itself fluctuates between 5 and 6 percent.

<!--See Figure 1 (c), next slide-->

## Recap: The Assumptions of Classical Economics

In Chapter 7, we saw that GDP depends on:

* number of workers
* physical capital per worker
* human capital per worker
* natural resources per worker
* technological knowledge
* laws, government policies, and their enforcement

In Chapter 8we saw that saving, investment, and the real interest rate depend on the supply and demand for loanable funds.

In Chapter 10 we saw that unemployment depends on:

* how well the labor market matches unemployed workers to job vacancies, and
* how close the wage is to the equilibrium wage.

In Chapter 12, we saw that: 

* the price level depends on the quantity of money, and the rate of inflation depends on the growth rate of the quantity of money, and
* the factors that affect the real interest rate (Ch. 8) and the inflation rate (Ch. 12) together determine the nominal interest rate.

## Explaining short-run economic fluctuations

Most economists believe that the long run theory we’ve studied in previous chapters does not explain short run fluctuations.
In the long run, changes in the money supply affect nominal variables but not real variables. 
This is monetary neutrality.
But most economists believe that monetary neutrality is not true in the short run.
Most economists believe that the central bank’s monetary policy:

* Has no effect on real variables (especially real GDP and unemployment) in the long run, but
* Has significant effects on real variables in the short run.

Video: [Intro to Business Fluctuations](https://youtu.be/vnUo82ZCo5s), Marginal Revolution University, YouTube, April 11, 2017.

## The Model of Aggregate Demand and Aggregate Supply

Economists use the model of aggregate demand and aggregate supply to explain short-run fluctuations in economic activity around its long-run trend.
Aggregate demand and aggregate supply are two ways in which real GDP and the overall price level are linked in the short run.

The _aggregate-demand curve_ shows the total quantity of “Made in USA” goods and services that everybody—households, firms, the government, and foreigners—wants to buy at each price level.
The _aggregate-supply curve_ shows the total quantity of “Made in USA” goods and services that US firms would like to produce and sell at each price level.

### The Aggregate-demand curve: Why the Aggregate-Demand Curve Slopes Downward

The aggregate demand for goods and services has four components:
\begin{equation}
\textrm{Aggregate Demand} = C + I + G + NX.
  (\#eq:aggregate-demand)
\end{equation}

Here we interpret $C$, $I$, $G$, and $NX$ as the _desired_ levels of consumption, investment, government purchases, and net exports.

<!--Figure 3 The Aggregate-Demand (AD) Curve is downward sloping-->

#### Why the demand curve for ice cream can’t explain the AD curve

The demand curve for an individual commodity is downward sloping because of two effects:

* Substitution effect: when ice cream becomes cheaper people buy more ice cream because they are switching from frozen yogurt (a substitute)
* Income effect: when price of ice cream falls and income is unchanged, people feel richer and, therefore, buy more ice cream

But the AD curve can consider only changes in the _overall_ price level. If _all_ prices decrease, there can be no substitution effect.

It is inconsistent to talk about changes in aggregate demand while assuming unchanged income, because aggregate income must be equal to aggregate demand. Therefore, the income effect can’t be applied to the aggregate economy.

The Aggregate-Demand Curve Slopes Downward because of:

* The Wealth Effect: a lower price level boosts consumption spending by households ($C$)
* The Interest-Rate Effect: a lower price level boosts investment spending by businesses ($I$)
* The Exchange-Rate Effect: a lower price level boosts net exports ($NX$)

As a result, a lower price level boosts aggregate demand ($C + I + G + NX$).

#### The Aggregate-demand curve: Why the Aggregate-Demand Curve Slopes Downward: The Price Level and Consumption: The Wealth Effect

If all prices fall ($P\downarrow$), the purchasing power of consumers’ monetary wealth increases.

This causes consumption spending to rise ($C\uparrow$)

Besides, if the price decline is perceived to be temporary it makes sense to buy what you need now, while prices are still low.

The rise in consumption spending ($C\uparrow$) raises aggregate demand ($C + I + G + NX\uparrow$).

Wealth Effect Controversy: Could the aggregate demand curve be _upward_ sloping?

$P\downarrow$ causes the real burden of the monetary debts of debtors to increase.
This causes debtors’ consumption to fall.
Therefore, if the decrease in debtors’ consumption exceeds the increase in the consumption of others, it is possible that consumption spending may fall $C\downarrow$.
Therefore, $P\downarrow$ could cause aggregate demand  to fall ($C+I+G+NX\downarrow$).
For this reason, the economist Paul Krugman has argued that the AD curve may in some cases be upward rising!

#### The Aggregate-demand curve: Why the Aggregate-Demand Curve Slopes Downward: The Price Level and Investment: The Interest-Rate Effect

When all prices _fall_, people need _less_ cash for shopping needs. They lend the unneeded cash. The increased availability of loans _reduces_ the interest rate. (See Ch. 16 for more on this. )

A lower interest rate encourages _greater_ investment spending by businesses ($I\uparrow$).
This rise in investment spending raises aggregate demand ($C + I + G + NX\uparrow$).

#### The Aggregate-demand curve: Why the Aggregate-Demand Curve Slopes Downward: The Price Level and Net Exports: The Exchange-Rate Effect

We saw above that lower prices lead to a lower interest rate. (See Ch. 16 for more on this.) 
Disappointed foreigners sell the dollars they had been holding in US banks.
The value of the dollar falls.
As a result, US goods become cheaper relative to foreign goods.
This makes U.S. net exports increase ($NX\uparrow$).
$NX\uparrow$ means aggregate demand rise ($C+I+G+NX\uparrow$).

## The Aggregate-demand curve: Why the Aggregate-Demand Curve Might Shift

Shifts of the aggregate demand curve could arise from changes in:

* Consumption: consumer optimism, tax rates, prices of assets (stocks, bonds, real estate)
* Investment: technological progress, business confidence, tax rates, money supply
* Government Purchases
* Net Exports: foreign GDP, expectations about exchange rates

Video: [The Aggregate Demand Curve](https://youtu.be/jL94Fdcdv1Y), Marginal Revolution University, YouTube, April 18, 2017. In this video, the growth rate of real GDP is measured on the horizontal axis and the growth rate of the price level (that is, inflation) is measured on the vertical axis.

## THE AGGREGATE-SUPPLY CURVE

The upward-sloping aggregate supply curve that we saw before is more precisely called the short-run aggregate-supply (SRAS) curve.

The long-run aggregate-supply (LRAS) curve is vertical.

<!--Figure 4 The Long-Run Aggregate-Supply Curve-->

### The Aggregate-Supply curve: Why the Aggregate-Supply Curve Is Vertical in the Long Run

An economy’s _long-run output_ of goods and services is also called the _natural rate of output_ or _potential output_ or _full-employment output_. (See Chapter 7.)

Long-run output depends on:

* labor
* physical capital
* human capital
* natural resources
* Technology
* Laws, government policies, and their enforcement

The price level does not affect these variables in the long run.

#### The Aggregate-SUPPLY curve: Why the Long-Run Aggregate-Supply Curve Might Shift

Any change in the economy that alters the natural rate of output will shift the long-run aggregate-supply curve. So, the long-run aggregate supply will shift because of changes in:

* Labor: population growth, immigration, natural rate of unemployment
* Capital, physical or human
* Natural Resources: price of imported oil
* Technology
* Laws, government policies

Video: [The Long-Run Aggregate Supply Curve](https://youtu.be/xqPpjR5X0ZY), Marginal Revolution University, YouTube, April 25, 2017. This LRAS has the growth rate of real GDP on the horizontal axis and the growth rate of the price level (inflation) on the vertical axis.

<!--Figure 5 Long-Run Growth and Inflation-->

### The Aggregate-Supply curve: Why the Aggregate-Supply Curve Slopes Upward in the Short Run

In the short run, an increase in the overall level of prices tends to raise the quantity of goods and services supplied.
A decrease in the level of prices tends to reduce the quantity of goods and services supplied.
Why?
<!--Figure 6 The Short-Run Aggregate-Supply Curve-->

Why the Aggregate-Supply Curve Slopes Upward in the Short Run:

* The Sticky-Wage Theory
* The Sticky-Price Theory
* The Misperceptions Theory

These are three different arguments, but they all reach the same conclusion:
\begin{equation}
Y = Y_N+a\times(P-P^e).
  (\#eq:SRAS)
\end{equation}

Note: If $P = P^e$, then $Y = Y_N$.

### The Aggregate-Supply curve: Why the Short-Run Aggregate-Supply Curve Might Shift

The SRAS curve shifts right if:

* The expected price falls, or
* The natural rate of output increases

#### The Aggregate-SUPPLY curve: Why the Aggregate-Supply Curve Slopes Upward in the Short Run: The Sticky-Wage Theory

Suppose wages for 2019 were agreed upon in 2018.
These 2018 wage agreements were based on the output prices that were expected to prevail in 2019.
Suppose, in 2019, actual prices turn out less than what had been expected (back in 2018).
Wages cannot adjust immediately to the unexpectedly low price level (because they were settled in 2018).
An unexpectedly low price level and an unchanged wage level makes employment and production less profitable.
This induces firms to reduce the quantity of goods and services supplied; workers lose jobs.

In other words, the short-run AS curve is upward rising.

Video: [Sticky Wages](https://youtu.be/IbiPQI0wMAk), Marginal Revolution University, YouTube, May 2, 2017

#### The Aggregate-SUPPLY curve: Why the Aggregate-Supply Curve Slopes Upward in the Short Run: The Sticky-Price Theory

As a result of menu costs (see Ch. 12), some firms may be unable to change their prices in response to changing economic conditions.
An unexpected fall in the overall price level leaves such firms with high prices relative to other firms that can quickly adjust their prices.
This depresses their sales, which induces these firms to reduce the quantity of goods and services they produce. 
Workers lose jobs.

#### The Aggregate-Supply curve: Why the Aggregate-Supply Curve Slopes Upward in the Short Run: The Misperceptions Theory

Suppose an overall decline in demand reduces all prices
A wheat farmer sees only that wheat prices have fallen and continues to believe that the prices of the things that she buys (milk, shoes, clothes, etc.) are unchanged at the level she had expected
This makes work less attractive and so the farmer reduces her production of wheat. 
I am assuming  that the wheat farmer knows only how to produce wheat
When this is repeated across the economy, both the overall price level and total output fall.

So, production decreases below the full-employment level when $P$ falls below $P^e$.
In other words, the AS curve is upward rising.

Video: [The Short-Run Aggregate Supply Curve](https://youtu.be/8oQxzHgceBA), Marginal Revolution University, YouTube, May 9, 2017. In this treatment, the SRAS has the growth rate of real GDP on the horizontal axis and the growth rate of the price level (inflation) on the vertical axis.

## Two causes of economic fluctuations

Focus on (a) long-run equilibrium, (b) short-run equilibrium following a disturbance that throws the economy off the long-run equilibrium, and (c) the readjustment to a new long-run equilibrium after the disturbance

<!--Figure 7 The Long-Run Equilibrium
Figure 8 A Contraction in Aggregate Demand-->

### Two causes of economic fluctuations: The Effects of a Shift in Aggregate Demand

When there is a contraction (leftward shift) in Aggregate Demand, these are the short run effects:

* output decreases, 
* the overall price level decreases, and 
* the unemployment rate increases

And these are the long run effects:

* the overall price level decreases, but 
* output and the unemployment rate  remain unchanged at their long-run levels. 

So, the economy heals itself in the long run. But it is unclear how long this self-healing might take.

If production and employment take too long to return to their long-run levels, the government could step in to hasten the process of healing.
The government could push the aggregate demand curve back where it was. It could do so by:

* increasing the money supply (expansionary monetary policy)
* cutting taxes or increasing government spending (expansionary fiscal policy)

<!--Figure 9 U.S. real GDP growth since 1900-->

#### History of Economic Fluctuations Caused by Changes in Aggregate Demand

In history, there have been two big shifts in aggregate demand: 

* Great Depression 
* World War II

The _Great Depression_ of the early 1930s was by far the worst economic downturn in US history.

From 1929 to 1933:

* Real GDP fell by 27%
* Unemployment rose from 3 to 25%
* Price level fell by 22%

Most historians blame a decrease in aggregate demand. Specifically, most historians blame  the 28% fall in the money supply.
People lost faith in the banking system and began to withdraw their money. Banks did not have the money to lend to businesses. Starved of loans, businesses shut down. Other businesses had to abandon expansion plans.
The Fed could have printed money and loaned it to the banks, but that did not happen.

Another suggested cause of the fall in aggregate demand during the Great Depression was the
Stock market crash. It led to a decrease in household wealth which led to a decrease in consumption spending which led to a decrease in aggregate demand.

In the case of _World War II_, the early 1940s saw a large increase in real GDP.

More resources were made available to the military.
Government purchases increased fivefold 1939 - 1944.
Aggregate demand – increased 1939 - 1944. This led to:

* Doubling of the economy’s production of goods and services.
* 20% increase in the price level
* Unemployment fell from 17% to 1%, lowest in US history

In the case of the Great Recession of 2008-09, the crisis of 2008 may have been caused by the Fed’s overreaction to the recession of 2001.
The Fed cut interest rates sharply at that time and kept them low for too long.
Those low interest rates may have fueled a ‘bubble’ in home prices.

Ther were significant developments in the mortgage market.
It became easier for subprime borrowers to get loans.
Borrowers with a higher risk of default (as indicated by income and credit history) received generous loans.
Securitization became prominent. It is a process by which a financial institution (mortgage originator) makes loan, and then another (investment bank) bundles them together into mortgage-backed securities.

The mortgage-backed securities were sold to other institutions, which may not have fully appreciated the risks in these securities.

Inadequate regulation of these high-risk loans, and misguided government policy
encouraged this high-risk lending.

During 1995-2006:

* Increase in housing demand
* Increase in housing prices, which more than doubled

During 2006-2009:

* housing prices fell 30%
* Substantial rise in mortgage defaults and home foreclosures
* Financial institutions that owned mortgage-backed securities suffered huge losses and stopped making loans

All this led to a large contractionary shift in the AD curve.

* Real GDP fell sharply: By 4.2% between the forth quarter of 2007 and the second quarter of 2009
* Employment fell sharply: Unemployment rate rose from 4.4% in May 2007 to 10.0% in October 2009 

Three policy actions were taken - aimed in part at returning AD to its previous level:

The Fed reacted as follows:

* Cut its target for the federal funds rate from 5.25% in September 2007 to about zero in December 2008
* Started buying mortgage-backed securities and other private loans in open-market operations
* Provided banks with additional funds
  
The U.S. Treasury reacted as follows:

In October 2008, Wall Street bailout \$700 billion was put in place. This was for the Treasury to use:

* to rescue the financial system
* To stem the financial crisis on Wall Street
* To make loans easier to obtain

The equity injections into banks meant that the U.S. government temporarily became a part owner of these banks.
  
In January 2009, President Barack Obama assumed office. He signed the \$787 billion stimulus bill, on February 17, 2009, to be spent over two years.

Recovery officially began June 2009.
But it was slow: average annual growth was 2.1% during 2009Q2 – 2015Q4.
Unemployment  fell to 5.0% by end of 2015, but employment-population ratio was unchanged.

Video: [The Great Recession](https://youtu.be/dI6HNi5I8d4), Marginal Revolution University, YouTube, August 9, 2016

### Two causes of economic fluctuations: The Effects of a Shift in Aggregate Supply

A leftward shift in Short-Run Aggregate Supply has the following effects:

* Output falls below the natural rate of output
* Unemployment rises
* The price level rises

If the government does nothing, the SRAS gradually shifts back to where it was. 
The price level, total production and unemployment is unaffected in the long run. 
<!--Figure 10 An Adverse Shift in Aggregate Supply-->

Leftward shifts in aggregate supply cause stagflation---a period of recession and inflation.
Output falls and prices rise.
Policymakers can influence aggregate demand. But they cannot offset both of these adverse effects simultaneously.

Policymakers may respond to a recession in one of the following ways:

* Do nothing and wait for prices and wages to adjust.
* Take action to increase aggregate demand by using (expansionary) monetary and fiscal policy.

<!--Figure 11 Accommodating an Adverse Shift in Aggregate Supply-->


#### John Maynard Keynes (1883-1946)

Our understanding of the short-run behavior of the economy grew out of economists’ attempts to understand why the Great Depression happened.
Published in 1936, Keynes’s _The General Theory of Employment, Interest and Money_ laid the foundations.

>“The long run is a misleading guide to current affairs. In the long run we are all dead. Economists set themselves too easy, too useless a task if in tempestuous seasons they can only tell us when the storm is long past, the ocean will be flat.”

>From "A Tract on Monetary Reform" by John Maynard Keynes (1923) 

Video: [Game of Theories: The Keynesians](https://youtu.be/cYNVB5iqydk), Marginal Revolution University, YouTube, November 7, 2017

Video: [Game of Theories: The Great Recession](https://youtu.be/_lsbJRmNcic), Marginal Revolution University, YouTube, December 5, 2017
