# Open-Economy Macroeconomics: Basic Concepts {#openecon}

## Prerequisites

Things you need to know before you see the rest of this presentation:

* The national income identity: $Y=C+I+G+NX$.
* The definition of national saving: $S=Y-C-G$.
* The quantity theory of money: In the long run, inflation = growth rate of the quantity of money – growth rate of inflation-adjusted GDP
* The nominal interest rate, the real interest rate, and the difference between them
* real interest rate = nominal interest rate – inflation 
* real interest rate, ex ante = nominal interest rate – expected inflation

## Definitions 

* Closed and open economies
* Exports, imports, net exports
* Trade balance, trade surplus, trade deficit, balanced trade
* Capital outflow, capital inflow, net capital outflow
* Exchange rates: nominal and real

### Definitions: Closed Economy

A closed economy is an economy that has no economic interactions with other economies

### Definitions: Open Economy

An open economy is an economy whose residents have regular economic interactions with residents of other economies.
There are cross-border purchases and sales of goods and services.
There are cross-border purchases and sales of financial assets such as stocks and bonds.
Some degree of migration may also occur.

### Definitions: Exports, Imports, Net Exports

Households, businesses, and government entities in open economies trade goods and services with foreigners.

* Exports = The market value of goods and services that are produced domestically and sold abroad.
* Imports = The market value of goods and services that are produced abroad and sold domestically.
* Net exports = Exports – Imports.
Net exports is also called the _trade balance_.

### Definitions: trade surplus, trade deficit, balanced trade

Net exports could be positive, negative, or zero. A country is said to have:

* A trade surplus when Net exports > 0. In this case, Exports > Imports.
* A trade deficit when Net exports < 0. In this case, Exports < Imports.
* Balanced trade when Net exports = 0. In this case, Exports = Imports.

Here are links to US data:

[Net exports of goods and services](https://fred.stlouisfed.org/series/A019RE1A156NBEA) 

[Exports of goods and services](https://fred.stlouisfed.org/series/B020RE1A156NBEA) 

[Imports of goods and services](https://fred.stlouisfed.org/series/B021RE1A156NBEA) 

### Definitions: Capital Outflow, Capital Inflow, Net Capital Outflow

Households, businesses, and government entities in open economies regularly trade financial and other assets with foreigners.

* Capital outflow = value of foreign assets purchased by domestic residents.
* Capital inflow = value of domestic assets purchased by foreign residents.
* Net capital outflow = capital outflow – capital inflow.

Net Capital Outflow:

* is NCO for short.
* Also called _net foreign investment_.
* Could be positive or negative or zero.

## An Accounting Identity: $NX = NCO$

It turns out that net exports and net capital outflow must always be equal.

Why?

An individual can’t get something for nothing, right?
The same is true for countries. 
A country can’t buy more goods, services, and assets from other countries than it sells to other countries.
This is the basic reason why $NX$ and $NCO$ must always be equal.

For every country, the value of goods and services purchased from other countries + the value of assets purchased from other countries = the value of goods and services sold to other countries + the value of assets sold to other countries.

Therefore, rearranging the terms, we see that the value of assets purchased from other countries – the value of assets sold to other countries = the value of goods and services sold to other countries – the value of goods and services purchased from other countries.

Therefore, net capital outflow = net exports!
In other words, $NX = NCO$.

One more time:

We just saw that, the value of assets purchased from other countries – the value of assets sold to other countries = the value of goods and services sold to other countries – the value of goods and services purchased from other countries.

Recall that:

* net capital outflow = the value of assets purchased from other countries – the value of assets sold to other countries, and 
* net exports = exports – imports.
Therefore, net capital outflow = net exports!

## An Accounting Identity: $S = I + NCO$

I assume that you are aware of the following important macroeconomic ideas:

* The national income identity: $Y = C + I + G + NX$.
* The definition of national saving: $S = Y - C - G$.

The national income identity says this: 

A country’s GDP (denoted $Y$) is the _market value_ of the total output of final goods and services, and is therefore also the _total expenditure_ on final goods and services. 
This total expenditure must be the sum of consumption spending by households ($C$), investment spending mainly by businesses ($I$), government purchases ($G$), and net exports ($NX$).

The definition of saving says this:

GDP, being total expenditure---as we just saw---is also total income. 
Income ($Y$) minus consumption by households ($C$) and consumption by the government ($G$) is the natural way to measure national saving ($S$).
Therefore, $S = Y - C - G$.

We can rewrite the national income identity as: $Y - C - G = I + NX$.
Using the definition of national saving, this becomes: $S = I + NX$.
And we have seen above that $NX = NCO$.
Therefore, we can write $S = I + NCO$.

This makes sense: 
A nation’s saving ($S$) must end up being loaned to domestic borrowers or foreign borrowers.
The loans made to domestic borrowers will end up as investment spending mainly by domestic firms ($I$).
And the loans made to foreigners will be net capital outflow ($NCO$).
Therefore,  $S = I + NCO$.

## Definition: Exchange Rates, Nominal and Real

We discussed exports, imports, and net exports earlier.
These are influenced by many factors including international prices.
The two most important international prices are:

* the nominal exchange rate and 
* the real exchange rate.

### Definition: Nominal Exchange Rates

The nominal exchange rate is the rate at which a person can trade the currency of one country for the currency of another.

The nominal exchange rate is expressed in two ways:

* In units of foreign currency per one U.S. dollar, and
* In units of U.S. dollars per one unit of the foreign currency.

On March 27, 2016 the exchange rate between the Japanese yen (¥) and the U.S. dollar was:

* \$1.00 = ¥113.16
* \$0.0088 = ¥1.00

#### Definition: Nominal Exchange Rates: Appreciation and Depreciation

* Appreciation is an _increase_ in the value of a currency (as measured by the amount of foreign currency it can buy).
* Depreciation is a _decrease_ in the value of a currency.

If the price of a dollar increases (say, from ¥100 to ¥120), it is an appreciation of the dollar.
If the price of a dollar decreases (say, from ¥100 to ¥80), it is a depreciation of the dollar.

#### Data on Nominal Exchange Rates

[Trade Weighted U.S. Dollar Index: Broad](https://research.stlouisfed.org/fred2/series/TWEXB)


### Definition: Real Exchange Rates

Recall that the nominal exchange rate is the rate at which a person can trade the _currency_ of one country for the _currency_ of another.
The real exchange rate is the rate at which a person can trade the _goods and services_ of one country for the _goods and services_ of another.

The real exchange rate expresses the prices of domestic goods not in currency units but in units of foreign goods.
If a case of German beer is twice as expensive as American beer, the US real exchange rate is 1/2 case of German beer per case of American beer.
Note that this expresses the price of a case of American beer in units of German beer.

Suppose:

* Price of U.S. wheat is $P$ = \$4.00 per ton
* Price of French wheat is $P^*$ = €2.00 per ton
* Price of a dollar is $e$ = €3.00 per dollar

Note that:
Price of a ton of U.S. wheat is \$4.00 or, equivalently, €12.00 (because each dollar is worth 3 euros).
Therefore, one ton of U.S. wheat costs the same as six tons of French wheat.
Therefore, the real exchange rate = 6.

How did we get 6 as the real exchange rate?
We multiplied 3 and 4 and divided the result by 2. 
That is, we calculated $e \times P / P^*$.
Therefore, we see that, in general, 
\begin{equation}
\textrm{Real Exchange Rate} = e \times P / P^*.
  (\#eq:real-exchange-rate)
\end{equation}

The real exchange rate depends on the nominal exchange rate and the prices of goods in the two countries, as measured in local currencies.
The real exchange rate is a key determinant of how much a country exports and imports.

#### Data: Real Exchange Rates

* [Real Broad Effective Exchange Rate for United States](https://research.stlouisfed.org/fred2/series/RBUSBIS) 
* [Real Narrow Effective Exchange Rate for United States](https://research.stlouisfed.org/fred2/series/RNUSBIS) 

## Theory: Effect of Real Exchange Rates on Net Exports

A depreciation (fall) in the U.S. real exchange rate means that U.S. goods have become cheaper relative to foreign goods.
This encourages consumers both at home and abroad to buy more U.S. goods and fewer goods from other countries.
As a result, U.S. exports rise, and U.S. imports fall. Therefore,
U.S. net exports increase.

Conversely, an appreciation in the U.S. real exchange rate means that U.S. goods have become more expensive compared to foreign goods.
So U.S. net exports fall.

### Theory: Purchasing-Power Parity

The purchasing-power parity theory is the simplest theory of exchange rates in the long run.

According to the purchasing-power parity theory, a unit of any given currency should buy the same quantity of goods in all countries. 

If a dollar buys 2 grams of gold in China and 5 grams of gold in Canada, one could:

* buy 5 grams of gold in Canada with a dollar, 
* sell 2 grams of gold in China and get back the dollar that was spent in Canada, and 
* still have 3 grams of gold left over!

All this buying in Canada and selling in China will eventually make the price of gold the same in the two countries.

The theory of purchasing-power parity is based on a principle called the _law of one price_.
According to the law of one price, a good must sell for the same price in all locations, once the prices are all expressed in the same currency. 
Consequently, a unit of any given currency should buy the same quantity of goods in all countries.

If the law of one price were not true, unexploited profit opportunities would exist.
If the same good sold at different prices in different countries, you could make money by simply buying the good where it is cheap and selling it where it is expensive.
The process of taking advantage of differences in prices in different markets is called _arbitrage_.

Price of a commodity in USA in \$ &times; ¥ per \$ exchange rate = Price of the commodity in USA in ¥.
If arbitrage occurs, eventually prices in two markets, expressed in the same currency, must become equal. Therefore:
Price of a commodity in USA in \$ × ¥ per \$ exchange rate = Price of the commodity in Japan in ¥.
(Price of a commodity in US in \$ × ¥ per \$ exchange rate)/(Price of the commodity in Japan in ¥)=1
Or, 
$$\frac{e\times P^*}{P}=1 $$.

We just saw that under purchasing-power parity, $e\times P^*/P=1$.
But we’ve seen that $e\times P^*/P$ is the real exchange rate! 
So, the purchasing-power parity theory says the real exchange rate must be equal to one.

>The theory of purchasing-power parity says that the real exchange rate, which is the price of domestic goods in units of foreign goods, must be equal to one, in the long run.

The net exports curve becomes horizontal at the long-run real exchange rate.

### Implications of Purchasing-Power Parity

We’ve just seen that in the long run $e\times P^*/P=1$.
This implies $e=P/P^*$.

Therefore, when $P\uparrow$ we have $e\downarrow$.
That is, when prices rise in a country, its currency will be worth less in terms of other currencies.

I assume you are aware of the quantity theory of money. 
It says that in the long run if the quantity of money in an economy increases faster than the output produced, then prices will rise.
That is, when the central bank of a country prints large quantities of money, the country’s money loses value in the sense that it buys fewer goods and services.
Moreover, as we saw above, the country’s money also loses value in the sense that it buys smaller amounts of other currencies.

<!--Figure 3 Money, Prices, and the Nominal Exchange Rate during the German Hyperinflation-->

### Limitations of Purchasing-Power Parity

We will discuss another long-run theory of the real exchange rate later.
The theory of purchasing-power parity, though intuitive, doesn’t fit the real world very well.
Many goods are not easily traded or shipped from one country to another.
Tradable goods are not always perfect substitutes when they are produced in different countries.

See the [web site for The Economist’s Big Mac Currency Index](https://www.economist.com/content/big-mac-index).

## What’s Next?

So far, we have seen a simple theory of the real exchange rate.
We need a more realistic theory of the real exchange rate.
Plus, we need a long-run theory of a country’s net exports.

